name: "CI"
on:
  push:
    paths-ignore:
      - "README.rst"
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  ci:
    runs-on: "ubuntu-latest"
    continue-on-error: "${{ matrix.experimental }}"
    strategy:
      fail-fast: false
      matrix:
        emacs-version:
          - "26.1"
          - "26.2"
          - "26.3"
          - "27.1"
          - "27.2"
          - "28.1"
          - "28.2"
          - "29.1"
          - "29.2"
          - "29.3"
          - "29.4"
          - "30.1"
          - "release-snapshot"
        experimental: [false]
        # include:
        #   - emacs-version: "snapshot"
        #     experimental: true

    steps:
      - uses: "actions/checkout@v4"

      - uses: "purcell/setup-emacs@master"
        with:
          version: "${{ matrix.emacs-version }}"

      - uses: "cask/setup-cask@master"
        with:
          version: "snapshot"

      - name: "Compile"
        run: |
          make compile

      - uses: "actions/setup-go@v5"
        with:
          go-version: "stable"
          check-latest: true
          cache: false

      - name: "Install tomljson"
        run: |
          go install github.com/pelletier/go-toml/v2/cmd/tomljson@latest

      - name: "Test"
        run: |
          make test
